name: Mindcrack Marathon KotL
version: 0.1
description: King of the Ladder for the Mindcrack Marathon/
author: Matthew Salsamendi

main: com.mcprohosting.plugins.kotl.KotL
database: false

commands:
   kotl:
     description: Managment commands for KotL
     permission: kotl
     usage: Syntax error! Type /imraising help for command reference.
permissions:
   kotl.*:
     description: Gives access to all KotL commands
     children:
       kotl.reset: true